# This is the service config file. It's where you define your service and its resources.

service: code-runner

frameworkVersion: "3"

provider:
  name: aws
  ecr:
    images:
      appimage:
        path: ./
  stage: dev
  region: us-west-1
  apiGateway:
    apiKeys:
      - ujApiKey

functions:
  cpp:
    image:
      name: appimage
      command:
        - app.cpp_handler
      entryPoint:
        - "/lambda-entrypoint.sh"
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: /code-runner/cpp
          method: post
          private: true
  java:
    image:
      name: appimage
      command:
        - app.java_handler
      entryPoint:
        - "/lambda-entrypoint.sh"
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: /code-runner/java
          method: post
          private: true
  python:
    image:
      name: appimage
      command:
        - app.python_handler
      entryPoint:
        - "/lambda-entrypoint.sh"
    timeout: 30
    memorySize: 1024
    events:
      - http:
          path: /code-runner/python
          method: post
          private: true
